// ==UserScript==
// @name         CSSBuy Copy Original Link
// @namespace    https://github.com/user/tampermonkey-scripts
// @version      1.0.0
// @description  Fügt einen Button hinzu, um den Original-Link eines Artikels auf CSSBuy in die Zwischenablage zu kopieren.
// @author       AutoGenerated
// @match        https://www.cssbuy.com/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=cssbuy.com
// @grant        GM_setClipboard
// @grant        GM_notification
// @run-at       document-end
// ==/UserScript==

(function () {
  'use strict';

  const TEXTS = {
    buttonLabel: 'Copy original link',
    copying: 'Copying…',
    copied: 'Original link copied!',
    missing: 'Original link not found on this page.'
  };

  const LABEL_PATTERNS = [/original\s+(?:link|url)/i, /item\s+(?:link|url)/i, /product\s+(?:link|url)/i, /source\s+(?:link|url)/i];

  const LINK_DOMAINS = ['item.taobao.com', 'tmall.com', 'jd.com', '1688.com', 'weidian.com', 'world.taobao.com'];
  const IGNORED_DOMAINS = ['cssbuy.com', 'www.cssbuy.com', 'm.cssbuy.com'];
  const NESTED_PARAMS = ['url', 'target', 'u', 'origin', 'src', 'link', 'jump', 'redirect'];
  const URL_IN_TEXT = /https?:\/\/[^\s"'>)]+/i;

  const STATE = {
    button: null,
    lastKnownLink: null,
    observer: null
  };

  function debounce(fn, delay) {
    let timeout;
    return function (...args) {
      clearTimeout(timeout);
      timeout = setTimeout(() => fn.apply(this, args), delay);
    };
  }

  function sanitizeUrl(url) {
    if (!url) return '';
    return url.trim().replace(/[)\]]+$/, '');
  }

  function unwrapNestedUrl(url) {
    const sanitized = sanitizeUrl(url);
    try {
      const parsed = new URL(sanitized, window.location.href);
      for (const param of NESTED_PARAMS) {
        const nestedValue = parsed.searchParams.get(param);
        if (nestedValue) {
          const decoded = sanitizeUrl(decodeURIComponent(nestedValue));
          if (isLikelyOriginalLink(decoded)) {
            return decoded;
          }
        }
      }
    } catch (error) {
      // ignore parsing issues and return the sanitized url
    }
    return sanitized;
  }

  function extractFromAttributes(element) {
    if (!element) return null;
    const attributeNames = ['data-original-url', 'data-origin-url', 'data-url', 'href', 'value'];
    for (const attr of attributeNames) {
      const value = element.getAttribute && element.getAttribute(attr);
      if (value) {
        const candidate = unwrapNestedUrl(value);
        if (candidate && isLikelyOriginalLink(candidate)) {
          return candidate;
        }
      }
    }

    if ('value' in element && typeof element.value === 'string') {
      const candidate = unwrapNestedUrl(element.value);
      if (candidate && isLikelyOriginalLink(candidate)) {
        return candidate;
      }
    }
    return null;
  }

  function isLikelyOriginalLink(url) {
    if (!url) return false;
    try {
      const parsed = new URL(url, window.location.href);
      if (!/^https?:/i.test(parsed.protocol)) return false;
      const host = parsed.hostname.toLowerCase();
      if (IGNORED_DOMAINS.some((domain) => host.includes(domain))) return false;
      if (LINK_DOMAINS.some((domain) => host.includes(domain))) return true;
      return host !== window.location.hostname.toLowerCase();
    } catch (error) {
      return false;
    }
  }

  function textMatchesOriginalLabel(text) {
    if (!text) return false;
    const trimmed = text.trim();
    if (!trimmed) return false;
    return LABEL_PATTERNS.some((pattern) => pattern.test(trimmed));
  }

  function findNearestLinkElement(labelElement) {
    if (!labelElement) return null;
    let current = labelElement;
    for (let depth = 0; depth < 5 && current; depth += 1) {
      const anchor = current.querySelector && current.querySelector('a[href], input[value], textarea');
      if (anchor) return anchor;
      current = current.parentElement;
    }
    return null;
  }

  function findOriginalLink() {
    const directElements = document.querySelectorAll('[data-original-url], [data-origin-url], [data-url], a[href], input[value], textarea');

    for (const element of directElements) {
      const candidate = extractFromAttributes(element);
      if (candidate) {
        STATE.lastKnownLink = candidate;
        return candidate;
      }
    }

    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_ELEMENT, null);
    while (walker.nextNode()) {
      const node = walker.currentNode;
      if (!node) continue;

      if (textMatchesOriginalLabel(node.textContent)) {
        const relatedElement = findNearestLinkElement(node);
        if (relatedElement) {
          const candidateFromAttributes = extractFromAttributes(relatedElement);
          if (candidateFromAttributes) {
            STATE.lastKnownLink = candidateFromAttributes;
            return STATE.lastKnownLink;
          }

          const candidateFromText = extractUrlFromText(relatedElement.textContent);
          if (candidateFromText) {
            STATE.lastKnownLink = candidateFromText;
            return STATE.lastKnownLink;
          }
        }
      }
    }

    const anchorCandidates = Array.from(document.querySelectorAll('a[href^="http"]'));
    for (const anchor of anchorCandidates) {
      const href = anchor.getAttribute('href');
      if (isLikelyOriginalLink(href)) {
        const textContent = anchor.textContent || '';
        if (!textContent || textMatchesOriginalLabel(textContent)) {
          STATE.lastKnownLink = unwrapNestedUrl(href);
          return STATE.lastKnownLink;
        }
      }
    }

    return STATE.lastKnownLink;
  }

  function extractUrlFromText(text) {
    if (!text) return null;
    const match = text.match(URL_IN_TEXT);
    if (!match) return null;
    const candidate = unwrapNestedUrl(match[0]);
    if (candidate && isLikelyOriginalLink(candidate)) {
      return candidate;
    }
    return null;
  }

  function createButton() {
    if (STATE.button) return STATE.button;

    const button = document.createElement('button');
    button.type = 'button';
    button.textContent = TEXTS.buttonLabel;
    button.style.cursor = 'pointer';
    button.style.padding = '8px 12px';
    button.style.margin = '8px';
    button.style.border = '1px solid #1a73e8';
    button.style.borderRadius = '4px';
    button.style.background = '#1a73e8';
    button.style.color = '#fff';
    button.style.fontSize = '14px';
    button.style.fontWeight = '600';
    button.style.transition = 'background-color 0.2s ease, transform 0.2s ease';
    button.style.boxShadow = '0 2px 6px rgba(26, 115, 232, 0.3)';
    button.style.zIndex = '9999';

    button.addEventListener('mouseenter', () => {
      button.style.background = '#1669c1';
      button.style.transform = 'translateY(-1px)';
    });

    button.addEventListener('mouseleave', () => {
      button.style.background = '#1a73e8';
      button.style.transform = 'translateY(0)';
    });

    button.addEventListener('click', handleButtonClick);

    STATE.button = button;
    return button;
  }

  async function copyToClipboard(text) {
    if (!text) throw new Error('No text to copy');

    if (typeof GM_setClipboard === 'function') {
      GM_setClipboard(text);
      return true;
    }

    if (navigator.clipboard && navigator.clipboard.writeText) {
      await navigator.clipboard.writeText(text);
      return true;
    }

    const textarea = document.createElement('textarea');
    textarea.value = text;
    textarea.setAttribute('readonly', '');
    textarea.style.position = 'absolute';
    textarea.style.left = '-9999px';
    document.body.appendChild(textarea);
    textarea.select();
    const success = document.execCommand('copy');
    document.body.removeChild(textarea);
    if (!success) throw new Error('Fallback copy failed');
    return success;
  }

  function notify(message, isError = false) {
    if (typeof GM_notification === 'function') {
      GM_notification({
        title: 'CSSBuy',
        text: message,
        timeout: 2500,
        silent: !isError,
        image: 'https://www.cssbuy.com/favicon.ico'
      });
    } else {
      const existing = document.getElementById('cssbuy-copy-link-toast');
      if (existing) existing.remove();

      const toast = document.createElement('div');
      toast.id = 'cssbuy-copy-link-toast';
      toast.textContent = message;
      toast.style.position = 'fixed';
      toast.style.top = '20px';
      toast.style.right = '20px';
      toast.style.padding = '12px 16px';
      toast.style.background = isError ? 'rgba(211, 47, 47, 0.95)' : 'rgba(56, 142, 60, 0.95)';
      toast.style.color = '#fff';
      toast.style.fontSize = '14px';
      toast.style.borderRadius = '4px';
      toast.style.boxShadow = '0 4px 12px rgba(0,0,0,0.15)';
      toast.style.zIndex = '10000';
      document.body.appendChild(toast);
      setTimeout(() => toast.remove(), 2200);
    }
  }

  async function handleButtonClick(event) {
    event.preventDefault();
    const button = STATE.button;
    if (!button) return;

    button.disabled = true;
    const previousText = button.textContent;
    button.textContent = TEXTS.copying;

    try {
      const link = findOriginalLink();
      if (!link) throw new Error(TEXTS.missing);
      await copyToClipboard(link);
      button.textContent = TEXTS.copied;
      notify(TEXTS.copied);
    } catch (error) {
      const message = error && error.message ? error.message : TEXTS.missing;
      button.textContent = previousText;
      notify(message, true);
      console.error('[CSSBuy Copy Link]', error);
    } finally {
      setTimeout(() => {
        button.disabled = false;
        button.textContent = TEXTS.buttonLabel;
      }, 1500);
    }
  }

  function insertButton() {
    const button = createButton();
    if (!button.isConnected) {
      const targetSelectors = ['.detail-info', '.product-detail', '.item-detail', '.goods-info', '#__nuxt', 'body'];
      let inserted = false;

      for (const selector of targetSelectors) {
        const container = document.querySelector(selector);
        if (container) {
          container.insertBefore(button, container.firstChild);
          inserted = true;
          break;
        }
      }

      if (!inserted) {
        document.body.appendChild(button);
      }
    }
  }

  function observePage() {
    if (STATE.observer) return;

    const observer = new MutationObserver(
      debounce(() => {
        findOriginalLink();
        insertButton();
      }, 300)
    );

    observer.observe(document.body, { childList: true, subtree: true });
    STATE.observer = observer;
  }

  function initialize() {
    insertButton();
    findOriginalLink();
    observePage();
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initialize);
  } else {
    initialize();
  }
})();
